security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    # Configuration des fournisseurs d'utilisateurs
    providers:
        # Utilisez doctrine pour charger les utilisateurs depuis la base de données
        database_users:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email

    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # provider that you set earlier inside providers
            provider: database_users
            # Définir la méthode d'authentification (form_login, http_basic, etc.)
            form_login:
                login_path: app_login  
                check_path: app_login 
                default_target_path: app_dashboard
            custom_authenticator: App\Security\UserAuthenticator
            entry_point: App\Security\UserAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
       - { path: ^/user, roles: ROLE_USER }
       - { path: ^/admin, roles: ROLE_ADMIN }
