vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/userCar
    #        upload_destination: '%kernel.project_dir%/public/images/userCar'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
