controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
    methods: GET
    

user_new:
    path: /admin/users/new
    controller: App\Controller\Admin\UserCrudController::createUser

app_temoignages:
    path: /temoignages
    controller: App\Controller\TemoignagesController::index

app_usercar:
    path: /usercar
    controller: App\Controller\UserCarController::index
    methods: GET

