controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
    methods: GET
    

user_new:
    path: /admin/users/new
    controller: App\Controller\Admin\UserCrudController::createUser

app_temoignages:
    path: /temoignages
    controller: App\Controller\TemoignagesController::index

app_usercar:
    path: /usercar
    controller: App\Controller\UserCarController::index
    methods: ['GET', 'POST']

app_horaire:
    path: /horaire
    controller: App\Controller\HoraireController::index

admin_temoignages_approuver:
    path: /admin/temoignages/approuver/{id}
    controller: App\Controller\TemoignagesController::approuverTemoignages
    methods: POST  # Vous devriez utiliser POST pour des opérations de modification
    requirements:
        id: \d+  # Assurez-vous que l'ID est un nombre

admin_temoignages_desapprouver:
    path: /admin/temoignages/desapprouver/{id}
    controller: App\Controller\TemoignagesController::desapprouverTemoignages
    methods: POST  # Vous devriez utiliser POST pour des opérations de modification
    requirements:
        id: \d+  # Assurez-vous que l'ID est un nombre
        






