parameters:
    # ...

services:
    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Admin\UserCrudController:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'
            $passwordHasher: '@security.user_password_hasher'

    App\Controller\Admin\UserCarImageType: ~  





